baseURL: 'https://tycharlie.com/'
languageCode: 'en-us'
title: "Charlie's Play Ground"

module:
  imports:
    path: github.com/CaiJimmy/hugo-theme-stack/v3

Params:
  mainSections: 
    - post
  Sidebar:
    emoji: "ğŸ‘¨ğŸ»â€ğŸ’»"
    subtitle: Travel in the coding world
    compact: false
    avatar:
      src: img/avatar.png
  widgets:
    homepage:
      - type: search
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 20
  
  Comments:
    enabled: true
    provider: remark42
    remark42:
      host: https://comment.tycharlie.com
      site: tycharlie.com
      locale: en


menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -100
      params:
        icon: home
    - identifier: about
      name: About
      url: /about
      weight: -90
      params:
        icon: user

  Social:
    - identifier: github
      name: GitHub
      url: 'https://github.com/jkcharlie6679/'
      params:
        icon: brand-github
        newTab: true
    - identifier: gitlab
      name: Gitlab
      url: 'https://gitlab.com/jkcharlie6679/'
      params:
        icon: brand-gitlab
        newTab: true
    - identifier: linkedin
      name: linkedin
      url: 'https://www.linkedin.com/in/tsung-yu-chan-757776210/'
      params:
        icon: brand-linkedin
        newTab: true
